{% set name = "pyls-isort" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2192bd2203db00459f85eb329521feba58af63075d2dd10a051a4eccd000bba0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - isort
    - python
    - python-language-server

test:
  imports:
    - pyls_isort
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/paradoxxxzero/pyls-isort
  summary: Isort plugin for python-language-server
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
